package my.approach.team.error;

public enum ApiErrorCode {
    SGM_E_ACCESS_FORBIDDEN,
    SGM_E_API_COMM_FAILURE,
    SGM_E_INVALID_TOKEN,
    SGM_E_INVALID_PARAM,
    SGM_E_ILLEGAL_OPERATION,
    SGM_E_INVALID_CONTEXT_FOR_SUBSTANCE,
    SGM_E_PAGINATION_NOT_SUPPORTED,
    SGM_E_RESOURCE_NOT_FOUND,
    SGM_E_GENERIC_ERROR,
    SGM_E_UNMAPPED_PATH,
    SGM_E_UNKNOWN_ERROR,
    SGM_E_UNAUTHORIZED
}

